### PR TITLE
Detekt

### PR DESCRIPTION
**Pull request by ybelMekk**
Add a static code smeller detekt. Tuned the config a bit. Removed some TODOS and made them issues.
Code overall was all good. No big issues. Made some small changes.

### CODE REVIEW

**Comment by ybelMekk** [comment]
Prob. Could discuss if it is necessary? :D

**Review by tronghn — APPROVED** [review]
lgtm

**Comment by ybelMekk** [comment]
I see that `detekt-config.yml` could need some tuning, i will fix that, be right back 👍🏾

**Comment by ybelMekk** [comment]
Turned ut the repo could use some freshness.

**Review by jksolbakken — APPROVED** [review]

**Review by tronghn — APPROVED** [review]

**Review by tommytroen — APPROVED** [review]

**Pull request merged**
